[package]
name = "example_uses_document_features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
document-features = "0.2.7"

[features]
## Documented
feature = []

